# Default values for rook-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: "rook"
namespace: "rook"
versionTag: "v0.6.2"
domain: "nais.devillo.no"

cluster:
  dataDirHostPath: "/var/lib/kubernetes/rook"
  monCount: "3"
  nodeAffinity: "nais.io/storage-node"
  toleration: "nais.io/storage-node"
  deviceFilter: "sdb"

pool:
  name: replicapool
  replicatedSize: "3"

objectstore:
  name: objectstore
  replicatedSize: "2"
  gatewayInstances: "2"
  nodeAffinity: "nais.io/storage-node"
  toleration: "nais.io/storage-node"

