apiVersion: v1
kind: Namespace
annotations:
    "helm.sh/resource-policy": keep
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: rook.io/v1alpha1
kind: Cluster
annotations:
    "helm.sh/resource-policy": keep
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  versionTag: {{ .Values.versionTag }}
  dataDirHostPath: {{ .Values.cluster.dataDirHostPath }}
  # toggle to use hostNetwork
  hostNetwork: false
  # set the amount of mons to be started
  monCount: {{ .Values.cluster.monCount }}
# To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
# The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage' and
# tolerate taints with a key of 'storage-node'.
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: {{ .Values.cluster.nodeAffinity }}
              operator: Exists
#      podAffinity:
#      podAntiAffinity:
      tolerations:
      - key: {{ .Values.cluster.toleration }}
        operator: Exists
#    api:
#      nodeAffinity:
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#    mgr:
#      nodeAffinity:
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#    mon:
#      nodeAffinity:
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#    osd:
#      nodeAffinity:
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
  storage:                # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter: {{ .Values.cluster.deviceFilter }}
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
      {{- if .Values.cluster.databaseSizeMb }}
      databaseSizeMB: {{ .Values.cluster.databaseSizeMb }}
      {{- end}}
      {{- if .Values.cluster.journalSizeMb }}
      journalSizeMB: {{ .Values.cluster.journalSizeMb }}
      {{- end}}
#      databaseSizeMB: 1024 # this value can be removed for environments with normal sized disks (100 GB or larger)
#      journalSizeMB: 1024  # this value can be removed for environments with normal sized disks (20 GB or larger)
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
#    nodes:  
#    - name: "172.17.4.101"
#      directories:         # specific directores to use for storage can be specified for each node
#      - path: "/rook/storage-dir"
#    - name: "172.17.4.201"
#      devices:             # specific devices to use for storage can be specified for each node
#      - name: "sdb"
#      - name: "sdc"
#      storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
#        storeType: bluestore
#    - name: "172.17.4.301"
#      deviceFilter: "^sd."
