apiVersion: storage.k8s.io/v1
kind: StorageClass
annotations:
    "helm.sh/resource-policy": keep
metadata:
  name: rook-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rook.io/block
parameters:
  pool: {{ .Values.pool.name }}
  # Specify the Rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the name of the cluster.
  # This is also the namespace where the cluster will be
  clusterName: {{ .Values.namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  # fstype: ext4
